### ISSUE TITLE
Issues while building native extensions

### ISSUE THREAD

**Issue by Crenshinibon** [Comcast/xml-selector#2]
While installing xml-selector via NPM I get a bunch of node-gyp errors in the console, possibly because of nan?

npm-debug.log has the following lines:

> 30213 error Linux 4.2.0-25-generic
> 30214 error argv "/home/dirk/.nvm/versions/node/v5.8.0/bin/node" "/home/dirk/.nvm/versions/node/v5.8.0/bin/npm" "install"
> 30215 error node v5.8.0
> 30216 error npm  v3.7.3
> 30217 error code ELIFECYCLE
> 30218 error xml-selector@0.3.0 install: `node-gyp rebuild`
> 30218 error Exit status 1
> 30219 error Failed at the xml-selector@0.3.0 install script 'node-gyp rebuild'.
> 30219 error Make sure you have the latest version of node.js and npm installed.
> 30219 error If you do, this is most likely a problem with the xml-selector package,
> 30219 error not with npm itself.
> 30219 error Tell the author that this fails on your system:
> 30219 error     node-gyp rebuild
> 30219 error You can get information on how to open an issue for this project with:
> 30219 error     npm bugs xml-selector
> 30219 error Or if that isn't available, you can get their info via:
> 30219 error     npm owner ls xml-selector
> 30219 error There is likely additional logging output above.
> 30220 verbose exit [ 1, true ]

**Comment by swizzley** [comment]
12 warnings and 17 errors generated.
make: *** [Release/obj.target/xqjs/ext/CharacterData.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/xml-selector
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "install" "-g" "xml-selector"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE

**Comment by MrYakobo** [comment]
Getting this as well, both on Mac OS Sierra and Linux Mint 18.2. node-gyp fails.
node v8.4.0
npm  v5.4.1
